/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as App_rootRouteImport } from './routes/app/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppRisksIndexRouteImport } from './routes/app/risks/index'
import { Route as AppRisksNewRouteImport } from './routes/app/risks/new'
import { Route as AppRisksIdRouteImport } from './routes/app/risks/$id'

const App_rootRoute = App_rootRouteImport.update({
  id: '/app/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/app/calendar',
  path: '/app/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRisksIndexRoute = AppRisksIndexRouteImport.update({
  id: '/app/risks/',
  path: '/app/risks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRisksNewRoute = AppRisksNewRouteImport.update({
  id: '/app/risks/new',
  path: '/app/risks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRisksIdRoute = AppRisksIdRouteImport.update({
  id: '/app/risks/$id',
  path: '/app/risks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof App_rootRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/': typeof AppIndexRoute
  '/app/risks/$id': typeof AppRisksIdRoute
  '/app/risks/new': typeof AppRisksNewRoute
  '/app/risks/': typeof AppRisksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppIndexRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/risks/$id': typeof AppRisksIdRoute
  '/app/risks/new': typeof AppRisksNewRoute
  '/app/risks': typeof AppRisksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/__root': typeof App_rootRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/': typeof AppIndexRoute
  '/app/risks/$id': typeof AppRisksIdRoute
  '/app/risks/new': typeof AppRisksNewRoute
  '/app/risks/': typeof AppRisksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/calendar'
    | '/app/'
    | '/app/risks/$id'
    | '/app/risks/new'
    | '/app/risks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/calendar'
    | '/app/risks/$id'
    | '/app/risks/new'
    | '/app/risks'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/app/__root'
    | '/app/calendar'
    | '/app/'
    | '/app/risks/$id'
    | '/app/risks/new'
    | '/app/risks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  App_rootRoute: typeof App_rootRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRisksIdRoute: typeof AppRisksIdRoute
  AppRisksNewRoute: typeof AppRisksNewRoute
  AppRisksIndexRoute: typeof AppRisksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/__root': {
      id: '/app/__root'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof App_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/app/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/risks/': {
      id: '/app/risks/'
      path: '/app/risks'
      fullPath: '/app/risks/'
      preLoaderRoute: typeof AppRisksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/risks/new': {
      id: '/app/risks/new'
      path: '/app/risks/new'
      fullPath: '/app/risks/new'
      preLoaderRoute: typeof AppRisksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/risks/$id': {
      id: '/app/risks/$id'
      path: '/app/risks/$id'
      fullPath: '/app/risks/$id'
      preLoaderRoute: typeof AppRisksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  App_rootRoute: App_rootRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppIndexRoute: AppIndexRoute,
  AppRisksIdRoute: AppRisksIdRoute,
  AppRisksNewRoute: AppRisksNewRoute,
  AppRisksIndexRoute: AppRisksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
